### ISSUE TITLE
配信一覧が欲しい

### ISSUE THREAD

**Issue by MaineK00n** [ehimennlab/ProjectE-2019#65]
## WHY
- どんな配信が行われているかわからない

## WHAT
- 配信一覧を用意(home?)

**Comment by MaineK00n** [comment]
- volumeする
- nginx-rtmp-moduleは必要ない

**Comment by hayate242** [comment]
![Untitled (Draft)-1](https://user-images.githubusercontent.com/16438057/65790531-cc481500-e19a-11e9-984a-6137e544eae1.jpg)
![Untitled (Draft)-2](https://user-images.githubusercontent.com/16438057/65790532-cc481500-e19a-11e9-85b0-9121c1fc68a7.jpg)
