### ISSUE TITLE
配信終了機能の実装

### ISSUE THREAD

**Issue by hayate242** [ehimennlab/ProjectE-2019#89]
## WHY
- 現状では，配信終了しても，live一覧から配信中の動画リストが消えない

## WHAT
- 配信者の管理画面から，LIVEの削除をできるようにする．
- LIVE配信時に生成されるm3u8ファイルを監視して，それがなくなったらLIVE終了とする

**Comment by MaineK00n** [comment]
- 監視方法はどうする？
- OBSなどで放送後，streamをOBS側で切ったらm3u8は削除される？
- せっかくDBで配信リストを管理してるのなら，そちらをうまく活用できない？

**Comment by hayate242** [comment]
- streamをOBS側で切ったらm3u8は削除されます
- 監視方法は，volumeでrmptの/opt/data/hls/をphpコンテナにマウントして，m3u8があるか監視．なかったら，ライブ一覧に表示しない
- 配信者側の管理画面で配信停止を押したら，DBから配信リスト削除する<- ユーザ管理しないといけないのでログイン機能必須．#97にて実装

**Comment by MaineK00n** [comment]
> 監視方法は，volumeでrmptの/opt/data/hls/をphpコンテナにマウントして，m3u8があるか監視．
なかったら，ライブ一覧に表示しない

ファイル検知はだるそう
