### ISSUE TITLE
ログイン機能の実装

### ISSUE THREAD

**Issue by hayate242** [ehimennlab/ProjectE-2019#97]
## WHY
- 閲覧者と配信者を管理したい

## WHAT
- ログインの実装
- 動画のユーザ別管理(テーブルにユーザ情報追加)
- ユーザごとのリスト表示など

**Comment by MaineK00n** [comment]
こちらで登録ページは持ちたくないなと思ってるけど，どう？
サービス固有の登録は嫌だなあと．
Google, Twitter, (Facebook)とかでログインしたいところ

- https://qiita.com/TakahikoKawasaki/items/e37caf50776e00e733be
- https://readouble.com/laravel/6.0/ja/authentication.html
- https://readouble.com/laravel/6.0/ja/socialite.html
- https://qiita.com/LowSE01/items/7bb479cfe3a9ba7723d4

**Comment by hayate242** [comment]
なるほど，やってみますか

**Comment by hayate242** [comment]
https://github.com/ehimennlab/ProjectE-2019/issues/97#issuecomment-540493854
別にいらない？

**Comment by MaineK00n** [comment]
> 別にいらない？

こうする？
- Social Login
- サービスオリジナルのユーザ登録・ログイン

**Comment by hayate242** [comment]
両方できるようにするのが，無難ですかね
